version: '3'
services:
  top.api:
    image: docker.pkg.github.com/agaf89/nest/nest:develop
    container_name: top34
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env
